use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

platform :ios, '9.0'

target 'iosSinovoLibrary_Example' do
  pod 'iosSinovoLibrary', :path => '../'

  target 'iosSinovoLibrary_Tests' do
    inherit! :search_paths

    
  end
end
